name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Get Git Version
      uses: docker://gittools/gitversion:5.0.2-beta1-27-linux-centos-7-netcoreapp2.2
      with:
        args: /github/workspace /nofetch /exec /bin/sh /execargs "-c \"echo $GitVersion_FullSemVer > /github/workspace/version.txt\""
    - name: Package dependencies
      run: cat /home/runner/work/EnumMapper/EnumMapper/version.txt
    - name: build solution
      run: dotnet build -c Release EnumMapper.sln
    - name: test
      run: dotnet test -c Release ./EnumMapper.Tests/EnumMapper.Tests.csproj --no-build
